### ISSUE TITLE
geom_brace fails on datetimes

### ISSUE THREAD

**Issue by RoyalTS** [NicolasH2/ggbrace#4]
This seems like it ought to work but doesn't, presumably because `xstart` and `xend` are datetimes:

```r
> df
# A tibble: 3 x 3
  status    xstart              xend               
  <fct>     <dttm>              <dttm>             
1 projected 2021-05-03 00:00:00 2021-07-26 00:00:00
2 scheduled 2021-04-05 00:00:00 2021-05-02 23:59:59
3 made      2021-01-08 00:00:00 2021-04-04 23:59:59
```

```r
> geom_brace(
+     data = df,
+     inherit.aes=FALSE,
+     aes(xstart=xstart, xend=xend, label=status), ystart=0, yend=10
+   )
Error in xend - xstart : non-numeric argument to binary operator
```

**Comment by NicolasH2** [comment]
Hi @RoyalTS, thanks for the question.
The problem here is not the dates, but rather that geom_brace only plots one single brace (right now it does not use mapping, though I might want to change that). For your purposes, stat_brace is better, though the df will have to be changed a little to have only one x column and a y column as well:

```r
df2 <- reshape2::melt(df)
df2$y <- rep(c(0,1), each=3)

df2

     status variable      value y
1 projected    xtart 2021-05-03 0
2 scheduled    xtart 2021-04-05 0
3      made    xtart 2021-01-08 0
4 projected     xend 2021-07-26 1
5 scheduled     xend 2021-05-02 1
6      made     xend 2021-04-04 1
```

stat_brace will take the highest and lowest value of x to define how to draw the brace. In this case, only the maximum y is used and the braced will be plotted a little above. You will need to define a parameter like color or linetype so that the braces are drawn inidivually for each status-type:

```r
ggplot() + stat_brace(mapping=aes(value, y, color=status), data=df2)

#OR, if you want the braces at a different y value, set the distance or outerstart parameter
ggplot() + stat_brace(mapping=aes(value, y, color=status), data=df2, outerstart=2)
```
![date_braces](https://user-images.githubusercontent.com/50340626/113504267-49460e80-9537-11eb-9dc4-bda43ed8400e.png)

I suppose you have actual data you plot and want to use the braces to indicate groups (like the status). In that case you can just use stat_brace on that:

```r
df2 <- reshape2::melt(df)
#just making up some data for the y values of your data points
df2$y <- rep(sample(1:10, nrow(df2)))

ggplot(df2, aes(value, y, color=status)) +
  geom_point() +
  stat_brace(outerstart = max(df2$y)+1)
```
![brace_data](https://user-images.githubusercontent.com/50340626/113504272-506d1c80-9537-11eb-9240-75258d2fe5e2.png)


Note: R will give a warning. I will update the package now to get rid of that.
```r
Warning message:
In if (names(mapping) %in% "label") { :
  the condition has length > 1 and only the first element will be used
```

**Comment by RoyalTS** [comment]
Thanks a ton for the detailed examples! Here's two things that are still tripping me up:

- it'd be great if `stat_brace()` and `geom_brace()` took `inherit.aes` as an argument like all the other geoms and stats
- The following errors for me on the latest `master` version of `ggbrace`:

```r
ggplot() + 
  ... +
  ggbrace::stat_brace(
    data = raw_data %>%
      group_by(status) %>%
      summarize(xstart=min(delivery_date), xend=max(delivery_date)) %>%
      tidyr::pivot_longer(-status) %>%
      mutate(y = if_else(name == 'xstart', 1e6, 0)),
    mapping = aes(value, y, label=status)
  )
```

```r
Error: geom_text requires the following missing aesthetics: label
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
geom_text requires the following missing aesthetics: label
Backtrace:
 1. (function (x, ...) ...
 2. ggplot2:::print.ggplot(x)
 4. ggplot2:::ggplot_build.ggplot(x)
 5. ggplot2:::by_layer(function(l, d) l$compute_geom_1(d))
 6. ggplot2:::f(l = layers[[i]], d = data[[i]])
 7. l$compute_geom_1(d)
 8. ggplot2:::f(..., self = self)
 9. ggplot2:::check_required_aesthetics(...)
 ```

(Let me know if I should whip up a more fully reproducible version of this.)

- Is there any way of making how the brace bends independent of the width of the brace? I currently have three braces of different widths that look like so:
<img width="313" alt="Screenshot 2021-04-04 at 20 16 00" src="https://user-images.githubusercontent.com/702580/113517881-ef6b3600-9582-11eb-8395-8f1b4fd67cbc.png">

**Comment by NicolasH2** [comment]
stat_brace actually already has inherit.aes=TRUE; I just hope I get to add the this to geom_brace soon as well.
- the error will go away if you add "group=status" in the aes (or color or linetype). I think this might not acutally be solvable otherwise
- I added a arguement "bending" to the functions. If set, all braces will have the same bending. The higher the rounder. Just take care not to set it too high or the braces will show zick-zack lines

All in all it could be generated like this:
```r
ggplot() + 
  stat_brace(aes(value, y, label=status, group=status), data=df2, 
             bending = 20, width=1, outerstart = 5)
```

**Comment by RoyalTS** [comment]
Hmm, I'm getting

```r
Warning messages:
1: Ignoring unknown parameters: inherit.aes 
```

when using `inherit.aes` with `stat_brace()`

Dito for `labelsize`, `labeldistance` and `labelcolor`, by the way.

What do I have to set `bending` to to get reasonable-looking rounding? For me it doesn't seem to ever bend at all.

**Comment by NicolasH2** [comment]
The bending value is the distance between the start of the curve and the end of its first bend. For dates it is a little more difficult...I used 5 for the dates you provided and it was ok, but you can try out any big or small numbers to get a feeling for it.

![brace_bending](https://user-images.githubusercontent.com/50340626/113521866-8abcd500-959c-11eb-9efa-58554690bc3f.png)

Ok, I see what you mean now. I just updated it, so it should all work now but to explain why it did not before:
- inherit.aes was set to TRUE without any option to change it.
- the different label options where called differently in stat_brace than in geom_brace (those you named were for geom_brace). It is actually good that you brought that up, I now streamlined it so both functions share mostly the same parameter names

**Comment by RoyalTS** [comment]
Brilliant! Thank you so much for the quick responses and all the work!
