### ISSUE TITLE
Braces under axes

### ISSUE THREAD

**Issue by RoyalTS** [NicolasH2/ggbrace#5]
I would love to be able to produce braces underneath the axes similar to this: https://rdrr.io/cran/lemon/man/brackets.html

Is this possible?

**Comment by NicolasH2** [comment]
Hi @RoyalTS,
right now this still has to be done manually, using two ggplot2 functions:

```r
df <- data.frame(x = 1:5, y = 1:5)     

ggplot(df, aes(x, y)) +
  geom_point() +
  stat_brace(rotate = 90, width=1) +
  coord_cartesian(x=range(data$x), clip = "off") + 
  theme(plot.margin = unit(c(0.5, 7, 0.5, 0.5), units="lines")) #other units would be "cm" etc.
```
![brace_outside](https://user-images.githubusercontent.com/50340626/113506781-23c10100-9547-11eb-8029-d1dc0cb2945b.png)

coord_cartesian:
- `x=range(data$x)` sets the limits of the plotting area (otherwise it would stretch to include the brace)
- `clip = "off"` sets the option to include things even if they are outside the plotting area

theme is used with its parameter plot.margin to set the exact margins for the plot and the outside area
- 1st number will add space above
- 2nd number will add space to the right
- 3rd number will add space below
- 4th number will add space to the left
- 0.5 comes close to the standard for ggplot

I want to include a function in the package to do this automatically, but because the space outside is defined by units like cm etc. this is hard to do automatically. Hopefully I find a way to do this soon, but for now this manual way is all I can think off.

**Comment by RoyalTS** [comment]
That did the trick! Thanks for that detailed explanation!

**Comment by iago-pssjd** [comment]
In this case you can do `range(data$x)` because `x` is a numerical variable, but what can be done when it is a factor?

**Comment by NicolasH2** [comment]
that's an excellent point. As of now, unfortunately, in order to use characters or factors, one would have to use the `seq_along` function to make things work.
That goes for the geom_brace and stat_brace functions as well as for the coord_cartesian

```r
library(ggbrace)
df <- data.frame(x = c("a","b","c","d","e"), y = 1:5)     

ggplot(df, aes(x, y)) +
  geom_point() +
  stat_brace(aes(x=seq_along(x)), rotate = 90, width=1) +
  coord_cartesian(x=range(seq_along(df$x)), clip = "off") + 
  theme(plot.margin = unit(c(0.5, 7, 0.5, 0.5), units="lines")) #other units would be "cm" etc.
```

**Comment by iago-pssjd** [comment]
@NicolasH2 thanks! I got my goal with your indication.
