### ISSUE TITLE
Warning that "parse" is ignored

### ISSUE THREAD

**Issue by sumtxt** [NicolasH2/ggbrace#8]
Hello! I combine `ggbrace` with the `latex2exp` package to have some Latex in the `geom_brace` label. This works just fine despite the fact that `geom_brace` says it ignores the parameter `parse=TRUE` (which it doesn't because when `parse=FALSE` the Latex does not render). Seems like that the warning message is misplaced. 

Example: 

```
library(ggbrace)
library(ggplot2)
library(latex2exp)

ggplot(mtcars, aes(mpg,drat)) + 
geom_point() + 
geom_brace(aes(
	x=c(1,2), 
	y=c(1,2), 
	label=TeX("$\\beta$", output = "character")), 
   	labelsize=10, 
	inherit.data=FALSE, 
    parse=TRUE)

Warning message:
In geom_brace(aes(x = c(1, 2), y = c(1, 2), label = TeX("$\\beta$",  :
  Ignoring unknown parameters: `parse`
```

**Comment by NicolasH2** [comment]
Hi @sumtxt,
I updated ggbrace so that the warning will no longer be displayed. Re-install the package to see the change.

Why this happened:
`geom_brace `and `stat_brace `each use 2 ggplot functions: 1 for making the path and 1 for displaying the text. The `...` argument in the brace function was directly transferred to the ggplot functions. So when a text-specific argument was given it would also go to the path which would then give a warning.
The issue has been solved by splitting the `...` input so that arguments only go to those ggplot functions that can use them.

Thanks a lot for your bringing this up :) This update definitely helps the package
